version: "3.7"
networks:
  default:
services:
  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      JELLYFIN_PublishedServerUrl: "${JELLYFIN_HOST}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/jellyfin:/config"
      - "${MEDIA_DIR}:/media"
  
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/navidrome:/data"
      - "${MEDIA_DIR}/Music:/music:ro"

  # https://hub.docker.com/r/linuxserver/prowlarr
  prowlarr:
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config"

  # https://docs.linuxserver.io/images/docker-nzbget
  nzbget:
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/nzbget:/config"
      - "${DOWNLOADS_DIR}:/downloads"

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/sonarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    links:
      - nzbget

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    links:
      - nzbget

  # https://docs.overseerr.dev/getting-started/installation
  # https://hub.docker.com/r/linuxserver/overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
    links:
      - sonarr
      - radarr
    networks:
      - default
