#!/bin/sh

# restore secrets to docker-compose.yml and traefik.toml after git commit

# install with:
#   ln -s ../../pre-commit .git/hooks/pre-commit
#   ln -s ../../post-commit .git/hooks/post-commit

for file in "docker-compose.yml" "traefik.toml"
do
	[ -e "${file}.bak" ] && mv "${file}.bak" "${file}"
	echo "restored secrets to ${file}"
done
