#!/bin/sh

# restore environment variables to .env files after git commit

# install with:
#   ln -s ../../pre-commit .git/hooks/pre-commit
#   ln -s ../../post-commit .git/hooks/post-commit

for file in *.env
do
	mv "${file}.bak" "${file}"
	echo "restored environment variables to ${file}"
done



