#!/bin/sh

# clean environment variables from .env files before git commit

# install with:
#   ln -s ../../pre-commit .git/hooks/pre-commit
#   ln -s ../../post-commit .git/hooks/post-commit

env_files="plex.env common.env"

for file in ${env_files}
do
	cp "${file}" "${file}.bak"
	sed -r -i "/^[[:space:]]*#/!s|([^=]+=).*|\1|g" "${file}"
done

echo "cleaned environment variables from ${env_files}"

git add ${env_files}