#!/bin/sh

# clean environment variables from .env files

env_files="plex.env common.env"

for file in ${env_files}
do
	cp "${file}" "${file}.bak"
	sed -r -i "s|([^#]+=).*|\1|g" "${file}"
done

echo "cleaned environment variables from ${env_files}"

git add ${env_files}