#!/bin/bash

cp docker-compose.yml docker-compose.yml.tmp

while IFS= read -r image
do
    sed -r "s|image: ${image%%:*}.*|image: ${image}|g" -i docker-compose.yml.tmp
done < .autoinc

docker-compose -f docker-compose.yml.tmp pull 

while IFS= read -r image
do
    sha="$(docker inspect --format='{{index .RepoDigests 0}}' $image)"
    sed -r "s|image: ${image%%:*}.*|image: ${sha}|g" -i docker-compose.yml.tmp
done < .autoinc

mv docker-compose.yml.tmp docker-compose.yml

docker-compose up -d